"""
Design System CSS Generator

Generates a CSS custom properties file with a complete design system
based on user-provided parameters (colors, fonts, scale).

Usage:
  python generate_design_system.py --output style-tokens.css
  python generate_design_system.py --primary "220, 70%, 50%" --font-display "Outfit" --font-body "DM Sans" --theme dark
  python generate_design_system.py --preset saas-dark --output tokens.css
  python generate_design_system.py --help

Presets: saas-dark, saas-light, portfolio-dark, portfolio-light, editorial, minimal
"""

import argparse
import sys
from pathlib import Path


PRESETS = {
    "saas-dark": {
        "primary": "220, 70%, 55%",
        "secondary": "280, 60%, 55%",
        "accent": "150, 70%, 50%",
        "bg": "220, 15%, 8%",
        "fg": "0, 0%, 95%",
        "font_display": "Plus Jakarta Sans",
        "font_body": "DM Sans",
        "font_mono": "JetBrains Mono",
        "radius_base": "8",
        "theme": "dark",
    },
    "saas-light": {
        "primary": "220, 70%, 45%",
        "secondary": "280, 50%, 50%",
        "accent": "150, 60%, 40%",
        "bg": "0, 0%, 98%",
        "fg": "220, 15%, 10%",
        "font_display": "Outfit",
        "font_body": "DM Sans",
        "font_mono": "Fira Code",
        "radius_base": "8",
        "theme": "light",
    },
    "portfolio-dark": {
        "primary": "0, 0%, 95%",
        "secondary": "45, 80%, 55%",
        "accent": "15, 90%, 55%",
        "bg": "0, 0%, 5%",
        "fg": "0, 0%, 90%",
        "font_display": "Clash Display",
        "font_body": "Manrope",
        "font_mono": "Space Mono",
        "radius_base": "4",
        "theme": "dark",
    },
    "portfolio-light": {
        "primary": "0, 0%, 10%",
        "secondary": "220, 50%, 50%",
        "accent": "15, 80%, 50%",
        "bg": "40, 20%, 97%",
        "fg": "0, 0%, 10%",
        "font_display": "Cabinet Grotesk",
        "font_body": "Work Sans",
        "font_mono": "IBM Plex Mono",
        "radius_base": "12",
        "theme": "light",
    },
    "editorial": {
        "primary": "0, 0%, 10%",
        "secondary": "15, 70%, 45%",
        "accent": "45, 80%, 50%",
        "bg": "40, 15%, 96%",
        "fg": "0, 0%, 10%",
        "font_display": "Playfair Display",
        "font_body": "Source Serif 4",
        "font_mono": "JetBrains Mono",
        "radius_base": "4",
        "theme": "light",
    },
    "minimal": {
        "primary": "0, 0%, 15%",
        "secondary": "0, 0%, 40%",
        "accent": "220, 60%, 50%",
        "bg": "0, 0%, 100%",
        "fg": "0, 0%, 8%",
        "font_display": "Instrument Serif",
        "font_body": "Geist Sans",
        "font_mono": "Geist Mono",
        "radius_base": "6",
        "theme": "light",
    },
}

# Major Third (1.250) type scale
TYPE_SCALE = {
    "xs": "0.75rem",  # 12px
    "sm": "0.875rem",  # 14px
    "base": "1rem",  # 16px
    "lg": "1.125rem",  # 18px
    "xl": "1.25rem",  # 20px
    "2xl": "1.5rem",  # 24px
    "3xl": "1.875rem",  # 30px
    "4xl": "2.25rem",  # 36px
    "5xl": "3rem",  # 48px
    "6xl": "3.75rem",  # 60px
    "7xl": "4.5rem",  # 72px
}

# 8px grid spacing
SPACING = {
    "0": "0",
    "0.5": "0.125rem",  # 2px
    "1": "0.25rem",  # 4px
    "2": "0.5rem",  # 8px
    "3": "0.75rem",  # 12px
    "4": "1rem",  # 16px
    "5": "1.25rem",  # 20px
    "6": "1.5rem",  # 24px
    "8": "2rem",  # 32px
    "10": "2.5rem",  # 40px
    "12": "3rem",  # 48px
    "16": "4rem",  # 64px
    "20": "5rem",  # 80px
    "24": "6rem",  # 96px
    "32": "8rem",  # 128px
    "40": "10rem",  # 160px
}


def generate_css(config: dict) -> str:
    """Generate complete CSS custom properties."""
    lines = []
    lines.append("/* ==========================================================")
    lines.append("   Design System Tokens")
    lines.append("   Generated by frontend-design skill")
    lines.append("   ========================================================== */")
    lines.append("")
    lines.append(":root {")

    # Colors
    lines.append("  /* --- Colors --- */")
    lines.append(f"  --color-primary: hsl({config['primary']});")
    lines.append(f"  --color-secondary: hsl({config['secondary']});")
    lines.append(f"  --color-accent: hsl({config['accent']});")
    lines.append(f"  --color-bg: hsl({config['bg']});")
    lines.append(f"  --color-fg: hsl({config['fg']});")
    lines.append(f"  --color-primary-hsl: {config['primary']};")
    lines.append(f"  --color-bg-hsl: {config['bg']};")
    lines.append(f"  --color-fg-hsl: {config['fg']};")

    # Surface colors
    if config["theme"] == "dark":
        lines.append("  --color-surface: hsl(220, 12%, 12%);")
        lines.append("  --color-surface-hover: hsl(220, 12%, 16%);")
        lines.append("  --color-border: hsl(220, 10%, 18%);")
        lines.append("  --color-muted: hsl(220, 10%, 40%);")
    else:
        lines.append("  --color-surface: hsl(0, 0%, 100%);")
        lines.append("  --color-surface-hover: hsl(0, 0%, 97%);")
        lines.append("  --color-border: hsl(0, 0%, 88%);")
        lines.append("  --color-muted: hsl(0, 0%, 55%);")

    # Semantic colors
    lines.append("  --color-success: hsl(142, 70%, 45%);")
    lines.append("  --color-warning: hsl(38, 92%, 50%);")
    lines.append("  --color-error: hsl(0, 72%, 51%);")
    lines.append("  --color-info: hsl(210, 92%, 55%);")
    lines.append("")

    # Typography
    lines.append("  /* --- Typography --- */")
    lines.append(f"  --font-display: '{config['font_display']}', sans-serif;")
    lines.append(f"  --font-body: '{config['font_body']}', sans-serif;")
    lines.append(f"  --font-mono: '{config['font_mono']}', monospace;")
    lines.append("")

    # Type scale
    lines.append("  /* --- Type Scale (Major Third 1.250) --- */")
    for name, value in TYPE_SCALE.items():
        lines.append(f"  --text-{name}: {value};")
    lines.append("")

    # Line heights
    lines.append("  /* --- Line Heights --- */")
    lines.append("  --leading-tight: 1.1;")
    lines.append("  --leading-snug: 1.25;")
    lines.append("  --leading-normal: 1.5;")
    lines.append("  --leading-relaxed: 1.65;")
    lines.append("  --leading-loose: 1.8;")
    lines.append("")

    # Letter spacing
    lines.append("  /* --- Letter Spacing --- */")
    lines.append("  --tracking-tight: -0.03em;")
    lines.append("  --tracking-normal: 0;")
    lines.append("  --tracking-wide: 0.05em;")
    lines.append("  --tracking-wider: 0.08em;")
    lines.append("")

    # Spacing
    lines.append("  /* --- Spacing (8px Grid) --- */")
    for name, value in SPACING.items():
        lines.append(f"  --space-{name}: {value};")
    lines.append("")

    # Border radius
    radius = int(config.get("radius_base", 8))
    lines.append("  /* --- Border Radius --- */")
    lines.append(f"  --radius-sm: {max(radius // 2, 2)}px;")
    lines.append(f"  --radius-md: {radius}px;")
    lines.append(f"  --radius-lg: {radius + 4}px;")
    lines.append(f"  --radius-xl: {radius + 8}px;")
    lines.append(f"  --radius-2xl: {radius + 12}px;")
    lines.append("  --radius-full: 999px;")
    lines.append("")

    # Sizing
    lines.append("  /* --- Component Sizing --- */")
    lines.append("  --size-btn-sm: 32px;")
    lines.append("  --size-btn-md: 40px;")
    lines.append("  --size-btn-lg: 48px;")
    lines.append("  --size-btn-xl: 56px;")
    lines.append("  --size-input: 40px;")
    lines.append("  --size-nav: 64px;")
    lines.append("")

    # Content widths
    lines.append("  /* --- Content Widths --- */")
    lines.append("  --width-prose: 65ch;")
    lines.append("  --width-content: 720px;")
    lines.append("  --width-page: 1200px;")
    lines.append("  --width-wide: 1400px;")
    lines.append("")

    # Animation
    lines.append("  /* --- Animation --- */")
    lines.append("  --duration-instant: 100ms;")
    lines.append("  --duration-fast: 200ms;")
    lines.append("  --duration-normal: 300ms;")
    lines.append("  --duration-slow: 500ms;")
    lines.append("  --duration-slower: 800ms;")
    lines.append("  --ease-out: cubic-bezier(0.16, 1, 0.3, 1);")
    lines.append("  --ease-in-out: cubic-bezier(0.33, 1, 0.68, 1);")
    lines.append("")

    # Shadows
    lines.append("  /* --- Shadows --- */")
    if config["theme"] == "dark":
        lines.append("  --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.3);")
        lines.append(
            "  --shadow-md: 0 4px 8px rgba(0, 0, 0, 0.3), 0 1px 2px rgba(0, 0, 0, 0.2);"
        )
        lines.append(
            "  --shadow-lg: 0 12px 24px rgba(0, 0, 0, 0.4), 0 4px 8px rgba(0, 0, 0, 0.2);"
        )
        lines.append(
            "  --shadow-xl: 0 24px 48px rgba(0, 0, 0, 0.5), 0 8px 16px rgba(0, 0, 0, 0.3);"
        )
    else:
        lines.append("  --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.06);")
        lines.append(
            "  --shadow-md: 0 4px 8px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.04);"
        )
        lines.append(
            "  --shadow-lg: 0 12px 24px rgba(0, 0, 0, 0.1), 0 4px 8px rgba(0, 0, 0, 0.06);"
        )
        lines.append(
            "  --shadow-xl: 0 24px 48px rgba(0, 0, 0, 0.15), 0 8px 16px rgba(0, 0, 0, 0.08);"
        )
    lines.append("")

    # Z-index
    lines.append("  /* --- Z-Index --- */")
    lines.append("  --z-dropdown: 50;")
    lines.append("  --z-sticky: 100;")
    lines.append("  --z-modal-backdrop: 200;")
    lines.append("  --z-modal: 300;")
    lines.append("  --z-toast: 400;")

    lines.append("}")
    lines.append("")

    # Base styles
    lines.append("/* --- Base Styles --- */")
    lines.append("body {")
    lines.append("  font-family: var(--font-body);")
    lines.append("  font-size: var(--text-base);")
    lines.append("  line-height: var(--leading-normal);")
    lines.append("  color: var(--color-fg);")
    lines.append("  background-color: var(--color-bg);")
    lines.append("  -webkit-font-smoothing: antialiased;")
    lines.append("  -moz-osx-font-smoothing: grayscale;")
    lines.append("}")
    lines.append("")
    lines.append("h1, h2, h3, h4, h5, h6 {")
    lines.append("  font-family: var(--font-display);")
    lines.append("  line-height: var(--leading-tight);")
    lines.append("  letter-spacing: var(--tracking-tight);")
    lines.append("}")
    lines.append("")
    lines.append("h1 { font-size: var(--text-5xl); font-weight: 700; }")
    lines.append("h2 { font-size: var(--text-4xl); font-weight: 700; }")
    lines.append("h3 { font-size: var(--text-3xl); font-weight: 600; }")
    lines.append("h4 { font-size: var(--text-2xl); font-weight: 600; }")
    lines.append("")

    # Reduced motion
    lines.append("/* --- Accessibility: Reduced Motion --- */")
    lines.append("@media (prefers-reduced-motion: reduce) {")
    lines.append("  *, *::before, *::after {")
    lines.append("    animation-duration: 0.01ms !important;")
    lines.append("    animation-iteration-count: 1 !important;")
    lines.append("    transition-duration: 0.01ms !important;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a CSS design system tokens file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=f"Available presets: {', '.join(PRESETS.keys())}",
    )
    parser.add_argument(
        "--output", "-o", default="design-tokens.css", help="Output CSS file path"
    )
    parser.add_argument(
        "--preset", choices=PRESETS.keys(), help="Use a preset configuration"
    )
    parser.add_argument(
        "--primary", help="Primary color HSL values, e.g. '220, 70%%, 50%%'"
    )
    parser.add_argument("--secondary", help="Secondary color HSL values")
    parser.add_argument("--accent", help="Accent color HSL values")
    parser.add_argument("--font-display", help="Display/heading font family name")
    parser.add_argument("--font-body", help="Body text font family name")
    parser.add_argument("--font-mono", help="Monospace font family name")
    parser.add_argument("--theme", choices=["light", "dark"], help="Theme mode")
    parser.add_argument("--radius", help="Base border radius in px")
    parser.add_argument(
        "--list-presets", action="store_true", help="List available presets and exit"
    )

    args = parser.parse_args()

    if args.list_presets:
        for name, preset in PRESETS.items():
            print(f"\n--- {name} ---")
            for key, val in preset.items():
                print(f"  {key}: {val}")
        sys.exit(0)

    # Start with preset or defaults
    if args.preset:
        config = PRESETS[args.preset].copy()
    else:
        config = PRESETS["saas-dark"].copy()

    # Override with CLI args
    if args.primary:
        config["primary"] = args.primary
    if args.secondary:
        config["secondary"] = args.secondary
    if args.accent:
        config["accent"] = args.accent
    if args.font_display:
        config["font_display"] = args.font_display
    if args.font_body:
        config["font_body"] = args.font_body
    if args.font_mono:
        config["font_mono"] = args.font_mono
    if args.theme:
        config["theme"] = args.theme
    if args.radius:
        config["radius_base"] = args.radius

    css = generate_css(config)
    output_path = Path(args.output)
    output_path.write_text(css, encoding="utf-8")
    print(f"Design system tokens written to: {output_path}")
    print(f"Preset: {args.preset or 'custom'}")
    print(f"Theme: {config['theme']}")
    print(f"Fonts: {config['font_display']} + {config['font_body']}")


if __name__ == "__main__":
    main()
